---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# suistats

The goal of suistats is to use of data from the Federal Statistical Office of Switzerland easier within R. But that is a long-term goal. We start with using their Swiss map. Find examples below.

Map data, municipality info and ZIP-code mapping data are all retrieved from [https://www.bfs.admin.ch](https://www.bfs.admin.ch).

## Installation

You can install it with:

``` r
devtools::install_github("tinino/suistats")
```

## Example
Plot municipalities:
```{r}
library(ggplot2)
library(suistats)
ggplot(data = make_layer_data(agg_level = "GDNR"),
       mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon() +
  geom_polygon(data = ch_shape_lake, fill = "deepskyblue") +
  geom_path(color = "white") +
  coord_equal()
```

Plot districts:
```{r}
ggplot(data = make_layer_data(agg_level = "BZNR"),
       mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon() +
  geom_polygon(data = ch_shape_lake, fill = "deepskyblue") +
  geom_path(color = "white") +
  coord_equal()
```

